### PR TITLE
Fixing og-image visualization on Twitter (X)

### LINKED ISSUE #130: OpenGraph Tag for Twitter preview looks bad
image

It would be really nice to solve this.

### PR DESCRIPTION
**Pull request by carneloot**
Fixing OpenGraph visualization for twitter. It now shows as a card.

image
I tested it using ngrok :)

I also took the opportunity to change the way the OpenGraph image is generated according to the NextJS 13 Docs [here](https://nextjs.org/docs/app/api-reference/file-conventions/metadata/opengraph-image#generate-images-using-code-js-ts-tsx). This removes the need to have @vercel/og as a depencency, so I removed it.

Fixes #130

### CODE REVIEW

**Review by ocodista — APPROVED** [review]

**Comment by ocodista** [comment]
@carneloot for some reason the build is failling.

I think it's because of the changes on yarn.lock.

Can you take a look at it?

output:

[13:36:41.768] Running build in Washington, D.C., USA (East) – iad1 (Hive)
[13:36:41.865] Cloning github.com/ocodista/trampar-de-casa (Branch: og-image, Commit: 935e14e)
[13:36:41.921] Skipping build cache, deployment was triggered without cache.
[13:36:43.548] Cloning completed: 1.683s
[13:36:43.829] Running "vercel build"
[13:36:44.274] Vercel CLI 32.4.1
[13:36:44.409] > Detected Turbo. Adjusting default settings...
[13:36:44.640] Running "install" command: `yarn install`...
[13:36:44.987] yarn install v1.22.17
[13:36:45.097] [1/4] Resolving packages...
[13:36:45.504] [2/4] Fetching packages...
[13:36:45.513] warning Pattern ["amqplib@latest"] is trying to unpack in the same destination "/vercel/.cache/yarn/v6/npm-amqplib-0.10.3-e186a2f74521eb55ec54db6d25ae82c29c1f911a-integrity/node_modules/amqplib" as pattern ["amqplib@^0.10.3","amqplib@^0.10.3","amqplib@^0.10.3","amqplib@^0.10.3"]. This could result in non-deterministic behavior, skipping.
[13:37:22.445] [3/4] Linking dependencies...
[13:37:22.447] warning "@turbo/gen > ts-node@10.9.1" has unmet peer dependency "@types/node@*".
[13:37:22.447] warning "@turbo/gen > ts-node@10.9.1" has unmet peer dependency "typescript@>=2.7".
[13:37:22.448] warning "eslint-config-custom > @typescript-eslint/eslint-plugin@5.62.0" has unmet peer dependency "@typescript-eslint/parser@^5.0.0".
[13:37:22.450] warning "eslint-config-custom > @typescript-eslint/eslint-plugin > tsutils@3.21.0" has unmet peer dependency "typescript@>=2.8.0 || >= 3.2.0-dev || >= 3.3.0-dev || >= 3.4.0-dev || >= 3.5.0-dev || >= 3.6.0-dev || >= 3.6.0-beta || >= 3.7.0-dev || >= 3.7.0-beta".
[13:37:22.450] warning "eslint-config-custom > eslint-config-next > @typescript-eslint/parser > @typescript-eslint/typescript-estree > ts-api-utils@1.0.2" has unmet peer dependency "typescript@>=4.2.0".
[13:37:22.453] warning "workspace-aggregator-5d410079-3568-4db4-881b-e9730443535b > web > @vitejs/plugin-react@4.0.4" has unmet peer dependency "vite@^4.2.0".
[13:37:22.493] warning Workspaces can only be enabled in private projects.
[13:37:22.493] warning Workspaces can only be enabled in private projects.
[13:37:22.493] warning Workspaces can only be enabled in private projects.
[13:37:22.494] warning Workspaces can only be enabled in private projects.
[13:37:22.494] warning Workspaces can only be enabled in private projects.
[13:37:35.440] [4/4] Building fresh packages...
[13:37:41.968] Done in 56.99s.
[13:37:42.010] Detected Next.js version: 13.4.19
[13:37:42.011] Running "turbo run build"
[13:37:42.335] • Packages in scope: web
[13:37:42.336] • Running build in 1 packages
[13:37:42.336] • Remote caching enabled
[13:37:42.336] web:build: cache bypass, force executing a3047e910b5d1cab
[13:37:42.516] web:build: yarn run v1.22.17
[13:37:42.546] web:build: $ next build
[13:37:43.074] web:build: - warn You have enabled experimental feature (serverActions) in next.config.js.
[13:37:43.074] web:build: - warn Experimental features are not covered by semver, and may cause unexpected or broken application behavior. Use at your own risk.
[13:37:43.074] web:build: 
[13:37:43.081] web:build: Attention: Next.js now collects completely anonymous telemetry regarding usage.
[13:37:43.081] web:build: This information is used to shape Next.js' roadmap and prioritize features.
[13:37:43.081] web:build: You can learn more, including how to opt-out if you'd not like to participate in this anonymous program, by visiting the following URL:
[13:37:43.081] web:build: https://nextjs.org/telemetry
[13:37:43.081] web:build: 
[13:37:43.170] web:build: - info Creating an optimized production build...
[13:38:03.938] web:build: - info Compiled successfully
[13:38:03.938] web:build: - info Linting and checking validity of types...
[13:38:08.711] web:build: 
[13:38:08.711] web:build: ./app/api/subscribers/db.ts
[13:38:08.711] web:build: 58:9  Warning: Unexpected console statement.  no-console
[13:38:08.711] web:build: 
[13:38:08.711] web:build: ./app/api/subscribers/optout/route.ts
[13:38:08.711] web:build: 25:5  Warning: Unexpected console statement.  no-console
[13:38:08.711] web:build: 
[13:38:08.711] web:build: ./app/components/AutoComplete.tsx
[13:38:08.711] web:build: 45:38  Warning: Unexpected any. Specify a different type.  @typescript-eslint/no-explicit-any
[13:38:08.711] web:build: 
[13:38:08.711] web:build: ./app/components/EmailForm.tsx
[13:38:08.712] web:build: 33:9  Warning: 'email' is assigned a value but never used.  @typescript-eslint/no-unused-vars
[13:38:08.712] web:build: 45:9  Warning: 'saveSubscriber' is assigned a value but never used.  @typescript-eslint/no-unused-vars
[13:38:08.712] web:build: 122:3  Warning: 'arg0' is defined but never used.  @typescript-eslint/no-unused-vars
[13:38:08.712] web:build: 
[13:38:08.712] web:build: ./app/components/ui/calendar.tsx
[13:38:08.712] web:build: 63:25  Warning: 'props' is defined but never used.  @typescript-eslint/no-unused-vars
[13:38:08.712] web:build: 64:26  Warning: 'props' is defined but never used.  @typescript-eslint/no-unused-vars
[13:38:08.712] web:build: 
[13:38:08.712] web:build: ./app/components/ui/radio-group.tsx
[13:38:08.712] web:build: 25:17  Warning: 'children' is defined but never used.  @typescript-eslint/no-unused-vars
[13:38:08.712] web:build: 
[13:38:08.712] web:build: ./app/landing-page/SubscribersCount.tsx
[13:38:08.712] web:build: 15:5  Warning: Unexpected console statement.  no-console
[13:38:08.712] web:build: 
[13:38:08.712] web:build: ./app/subscribers/profile/components/SubscriberForm.tsx
[13:38:08.713] web:build: 25:3  Warning: Unexpected console statement.  no-console
[13:38:08.715] web:build: 
[13:38:08.715] web:build: ./app/subscribers/profile/getSubscriber.ts
[13:38:08.715] web:build: 24:5  Warning: Unexpected console statement.  no-console
[13:38:08.715] web:build: 
[13:38:08.716] web:build: ./app/subscribers/profile/getSubscriberTopics.ts
[13:38:08.716] web:build: 24:5  Warning: Unexpected console statement.  no-console
[13:38:08.716] web:build: 
[13:38:08.716] web:build: ./app/subscribers/profile/getTopics.ts
[13:38:08.716] web:build: 18:5  Warning: Unexpected console statement.  no-console
[13:38:08.716] web:build: 
[13:38:08.716] web:build: info  - Need to disable some ESLint rules? Learn more here: https://nextjs.org/docs/basic-features/eslint#disabling-rules
[13:38:12.095] web:build: - info Collecting page data...
[13:38:13.134] web:build: - warn Using edge runtime on a page currently disables static generation for that page
[13:38:13.363] web:build: No storage option exists to persist the session, which may result in unexpected behavior when using auth.
[13:38:13.363] web:build:         If you want to set persistSession to true, please provide a storage option or you may set persistSession to false to disable this warning.
[13:38:13.387] web:build: No storage option exists to persist the session, which may result in unexpected behavior when using auth.
[13:38:13.388] web:build:         If you want to set persistSession to true, please provide a storage option or you may set persistSession to false to disable this warning.
[13:38:23.297] web:build: - info Generating static pages (0/9)
[13:38:23.357] web:build: - info Generating static pages (2/9)
[13:38:23.432] web:build: - info Generating static pages (4/9)
[13:38:23.496] web:build: - warn Entire page /subscribers/optout deopted into client-side rendering. https://nextjs.org/docs/messages/deopted-into-client-rendering /subscribers/optout
[13:38:23.502] web:build: - warn 
[13:38:23.502] web:build: metadata.metadataBase is not set for resolving social open graph or twitter images, using "https://trampar-de-casa-2c3xq1634-caiohoborghi.vercel.app". See https://nextjs.org/docs/app/api-reference/functions/generate-metadata#metadatabase
[13:38:23.514] web:build: TypeError: Failed to parse URL from /_next/static/media/Roboto.d0bc87a8.ttf
[13:38:23.515] web:build:     at new Request (node:internal/deps/undici/undici:7134:19)
[13:38:23.515] web:build:     at r (/vercel/path0/apps/web/.next/server/chunks/217.js:6322:65)
[13:38:23.515] web:build:     ... 5 lines matching cause stack trace ...
[13:38:23.515] web:build:     at async collectStaticImagesFiles (/vercel/path0/node_modules/next/dist/lib/metadata/resolve-metadata.js:207:80)
[13:38:23.516] web:build:     at async Promise.all (index 2)
[13:38:23.516] web:build:     at async resolveStaticMetadata (/vercel/path0/node_modules/next/dist/lib/metadata/resolve-metadata.js:212:47) {
[13:38:23.516] web:build:   [cause]: TypeError [ERR_INVALID_URL]: Invalid URL
[13:38:23.516] web:build:       at new NodeError (node:internal/errors:405:5)
[13:38:23.517] web:build:       at new URL (node:internal/url:611:13)
[13:38:23.517] web:build:       at new Request (node:internal/deps/undici/undici:7132:25)
[13:38:23.517] web:build:       at r (/vercel/path0/apps/web/.next/server/chunks/217.js:6322:65)
[13:38:23.517] web:build:       at 72141 (/vercel/path0/apps/web/.next/server/chunks/435.js:984:14)
[13:38:23.518] web:build:       at Function.__webpack_require__ (/vercel/path0/apps/web/.next/server/webpack-runtime.js:25:43)
[13:38:23.518] web:build:       at async tree.children.metadata.openGraph (/vercel/path0/apps/web/.next/server/app/subscribers/optout/page.js:314:36)
[13:38:23.518] web:build:       at async /vercel/path0/node_modules/next/dist/lib/metadata/resolve-metadata.js:206:102
[13:38:23.518] web:build:       at async Promise.all (index 0)
[13:38:23.518] web:build:       at async collectStaticImagesFiles (/vercel/path0/node_modules/next/dist/lib/metadata/resolve-metadata.js:207:80) {
[13:38:23.519] web:build:     input: '/_next/static/media/Roboto.d0bc87a8.ttf',
[13:38:23.519] web:build:     code: 'ERR_INVALID_URL'
[13:38:23.519] web:build:   }
[13:38:23.519] web:build: }
[13:38:23.528] web:build: TypeError: Failed to parse URL from /_next/static/media/Roboto.d0bc87a8.ttf
[13:38:23.528] web:build:     at new Request (node:internal/deps/undici/undici:7134:19)
[13:38:23.529] web:build:     at r (/vercel/path0/apps/web/.next/server/chunks/217.js:6322:65)
[13:38:23.529] web:build:     ... 5 lines matching cause stack trace ...
[13:38:23.529] web:build:     at async collectStaticImagesFiles (/vercel/path0/node_modules/next/dist/lib/metadata/resolve-metadata.js:207:80)
[13:38:23.529] web:build:     at async Promise.all (index 2)
[13:38:23.529] web:build:     at async resolveStaticMetadata (/vercel/path0/node_modules/next/dist/lib/metadata/resolve-metadata.js:212:47) {
[13:38:23.529] web:build:   [cause]: TypeError [ERR_INVALID_URL]: Invalid URL
[13:38:23.529] web:build:       at new NodeError (node:internal/errors:405:5)
[13:38:23.529] web:build:       at new URL (node:internal/url:611:13)
[13:38:23.529] web:build:       at new Request (node:internal/deps/undici/undici:7132:25)
[13:38:23.530] web:build:       at r (/vercel/path0/apps/web/.next/server/chunks/217.js:6322:65)
[13:38:23.530] web:build:       at 72141 (/vercel/path0/apps/web/.next/server/chunks/435.js:984:14)
[13:38:23.530] web:build:       at Function.__webpack_require__ (/vercel/path0/apps/web/.next/server/webpack-runtime.js:25:43)
[13:38:23.530] web:build:       at async tree.children.metadata.openGraph (/vercel/path0/apps/web/.next/server/app/subscribers/optout/page.js:314:36)
[13:38:23.530] web:build:       at async /vercel/path0/node_modules/next/dist/lib/metadata/resolve-metadata.js:206:102
[13:38:23.530] web:build:       at async Promise.all (index 0)
[13:38:23.530] web:build:       at async collectStaticImagesFiles (/vercel/path0/node_modules/next/dist/lib/metadata/resolve-metadata.js:207:80) {
[13:38:23.530] web:build:     input: '/_next/static/media/Roboto.d0bc87a8.ttf',
[13:38:23.530] web:build:     code: 'ERR_INVALID_URL'
[13:38:23.530] web:build:   }
[13:38:23.530] web:build: }
[13:38:23.532] web:build: [Error: An error occurred in the Server Components render. The specific message is omitted in production builds to avoid leaking sensitive details. A digest property is included on this error instance which may provide additional details about the nature of the error.] {
[13:38:23.532] web:build:   digest: '2242811250'
[13:38:23.533] web:build: }
[13:38:23.533] web:build: 
[13:38:23.533] web:build: Error occurred prerendering page "/subscribers/optout". Read more: https://nextjs.org/docs/messages/prerender-error
[13:38:23.533] web:build: Error: An error occurred in the Server Components render. The specific message is omitted in production builds to avoid leaking sensitive details. A digest property is included on this error instance which may provide additional details about the nature of the error.
[13:38:23.535] web:build: - warn 
[13:38:23.535] web:build: metadata.metadataBase is not set for resolving social open graph or twitter images, using "https://trampar-de-casa-2c3xq1634-caiohoborghi.vercel.app". See https://nextjs.org/docs/app/api-reference/functions/generate-metadata#metadatabase
[13:38:23.543] web:build: - info Generating static pages (6/9)
[13:38:23.556] web:build: - warn Entire page /confirma-email deopted into client-side rendering. https://nextjs.org/docs/messages/deopted-into-client-rendering /confirma-email
[13:38:23.726] web:build: - info Generating static pages (9/9)
[13:38:23.730] web:build: 
[13:38:23.730] web:build: > Export encountered errors on following paths:
[13:38:23.731] web:build: 	/subscribers/optout/page: /subscribers/optout
[13:38:23.809] web:build: error Command failed with exit code 1.
[13:38:23.810] web:build: info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
[13:38:23.827] web:build: ERROR: command finished with error: command (/vercel/path0/apps/web) yarn run build exited (1)
[13:38:23.828] web#build: command (/vercel/path0/apps/web) yarn run build exited (1)
[13:38:23.829] 
[13:38:23.829]   Tasks:    0 successful, 1 total
[13:38:23.829]  Cached:    0 cached, 1 total
[13:38:23.829]    Time:    41.73s 
[13:38:23.829] Summary:    /vercel/path0/.turbo/runs/2WOiwAyJ7tKtDswlQJIPIlERsJM.json
[13:38:23.830]  Failed:    web#build
[13:38:23.830] 
[13:38:23.830]  ERROR  run failed: command  exited (1)
[13:38:23.838] Error: Command "turbo run build" exited with 1

**Comment by carneloot** [comment]
@ocodista fixed it!

I was able to build locally successfully, so it should work now.

**Comment by ocodista** [comment]
Thank you!!!

We have a different error now, is there a way to make the image smaller?

image

**Comment by carneloot** [comment]
I tried converting the image to jpg to get a smaller bundle size. Apparently next's ImageResponse doesn't support webp images, which is a shame since it would be the better option.

Kinda hard to test this one, but I hope it works.

**Comment by ocodista** [comment]
That works, thank you @carneloot !

**Pull request merged**
