### PR TITLE
feat: scroll to top button

### PR DESCRIPTION
**Pull request by albertofp**
#76

Adds scroll to top button.  Styling is WIP

Preview:
image
image

### CODE REVIEW

**Comment by gahcalistro** [comment]
@albertofp I would recommend a cleanup in the useEffect hook just for performance purposes. Also declare the callback function of the listener outside itself, this will help readability.

Something like this:
```
useEffect(() => {
  window.addEventListener("scroll", handleScroll)

  return () => window.addEventListener("scroll", handleScroll)
},[])

const handleScroll = () => {
  // code
}
```

**Comment by ocodista** [comment]
> @albertofp I would recommend a cleanup in the useEffect hook just for performance purposes. Also declare the callback function of the listener outside itself, this will help readability.
> 
> Something like this:
> 
> ```
> useEffect(() => {
>   window.addEventListener("scroll", handleScroll)
> 
>   return () => window.addEventListener("scroll", handleScroll)
> },[])
> 
> const handleScroll = () => {
>   // code
> }
> ```

I think it should be

```
return () => window.removeEventListener("scroll", handleScroll)
```

**Comment by gahcalistro** [comment]
> > @albertofp I would recommend a cleanup in the useEffect hook just for performance purposes. Also declare the callback function of the listener outside itself, this will help readability.
> > Something like this:
> > ```
> > useEffect(() => {
> >   window.addEventListener("scroll", handleScroll)
> > 
> >   return () => window.addEventListener("scroll", handleScroll)
> > },[])
> > 
> > const handleScroll = () => {
> >   // code
> > }
> > ```
> 
> I think it should be
> 
> ```
> return () => window.removeEventListener("scroll", handleScroll)
> ```

That's right, my bad. It should remove eventListener in the cleanup.

**Comment by albertofp** [comment]
You're right, thanks for the heads up.

**Review by ocodista — APPROVED** [review]

**Pull request merged**
