### PR TITLE
feat: style global error page

### PR DESCRIPTION
**Pull request by Lucas-Onofre**
I added styling to the global error page, following the foundation of the Tailwind UI's "Not Found Error" template.

image

### CODE REVIEW

**Comment by anti-duhring** [comment]
Nice! Is it responsive?

**Comment by ocodista** [comment]
The lint of this PR seems odd.

We shouldn't be replacing single quotes with double quoter, neither be adding a ';' at the end of each line, would you please take a look at this?

**Comment by anti-duhring** [comment]
> Nice! Is it responsive?

@Lucas-Onofre

**Comment by ocodista** [comment]
@Lucas-Onofre Please add a screenshot of how this page looks like on mobile, or we'll need to close this PR.

**Pull request closed without merging**
