### PR TITLE
Chore/eslint and prettier

### PR DESCRIPTION
**Pull request by gabrielSouzaDevWeb**
modified eslintrc and add prettierrc

### CODE REVIEW

**Comment by ocodista** [comment]
I don't think that this is the right way to do it.

See, we are using turborepo as the manager of our monorepo.

We have 2 apps (that will be more in the future, but for now `web` and `manual-email-sender`) and 2 packages (1 is for shared eslint-config and 1 is the `shared` folder).

We use (or definitely will use in a near future):
- TypeScript
- ESLint
- Prettier
- Vite

Your PR configures only the app/web project, meaning that we'll need to do the same for the other apps/packages.

I see two possible ways of solving this:

## Config files on the root
- Delete eslint-config-custom package
- Add all config files at the root of the repo
- Use a `script` at the root package.json file to format/lint all files

### Benefits
- This way we ensure we're running the format/linter before every commit.
- We centralize the linting/formating to be on a root level, without having to manage/create multiple files inside of each package/folder

### Drawbacks
- The linting/formatting will only work if we have the entire monorepo open in the VSCode

## Shared config files
- Move the config files to the shared project
- Delete the eslint-config-custom package
- Create and import eslint config from this package on all apps/packages other than the shared
- Update the husky to lint/format all files

### Benefits
- Linting/formatting will work even if you have only one app/package open at the VSCode
- You can still have a pre-commit hook to ensure everything works fine

### Drawbacks
- You have to create, copy and paste all of the "local" eslint config files and point to the shared project


I'm not totally sure which one would be better.

Personally, as I don't see a problem having the entire repo opened in your editor, I think I like more the number 1 approach.

But the turborepo team https://turbo.build/repo/docs/handbook/linting/eslint suggests you to use the second one (although they don't explain why).

With that in mind, I would say go with the number 2.

@albertofp @anti-duhring @rafa-thayto What do you guys think?

**Comment by gabrielSouzaDevWeb** [comment]
I understand your point. Having the settings in the root of the mono repo can indeed be beneficial, especially when the entire mono repo is contained within a single repository on GitHub. In such a case, it makes sense to centralize the settings and configurations at the root level.

On the other hand, if the projects within the mono repo were versioned separately and each had its own GitHub repository, it would be more appropriate to have project-specific settings within each individual project.

Considering the current scenario with a single repository for the mono repo on GitHub, it would be more efficient to manage and maintain the settings at the root level. This approach simplifies the configuration process and ensures consistency across all projects within the mono repo.

**Comment by albertofp** [comment]
Personally I'm inclined to go with Option 1 (Settings at the Root level) but I see the benefits of going the other route.  And if the turborepo people prefer Option 2 I think that's even more reason.

It's my first time using Turborepo and working in a monorepo in general so I would  tend towards the "recommended" implementation

**Comment by ocodista** [comment]
@gabrielSouzaDevWeb thank you for opening this PR.

I tested your branch and the husky hook works, but we still have a few things that needs to be fixed before we can merge this guy.

- Remove the project packages/eslint-config-custom
- Fix the eslint errors that pop when you run `yarn lint-staged` on the root path of the repo.

**Comment by tgmarinho** [comment]
run eslint and prettier fix and commit the changes, then everyone will have the codebase updated with new rules

**Comment by tgmarinho** [comment]
if you will depete the eslint-custom package, I think you should delete this file: https://github.com/ocodista/trampar-de-casa/blob/main/packages/shared/.eslintrc.js

**Comment by anti-duhring** [comment]
I do prefer Option 1 cause I already work with the entire repo opened in VS Code and, to me, these kind of config files should always be the same to the entire codebase. I don't see any advantage to use these config files in shared folder unless we want to use different configurations to each one in the future.

**Comment by ocodista** [comment]
> I do prefer Option 1 cause I already work with the entire repo opened in VS Code and, to me, these kind of config files should always be the same to the entire codebase. I don't see any advantage to use these config files in shared folder unless we want to use different configurations to each one in the future.

I'm ok with it.

It is the approach that @gabrielSouzaDevWeb used in this PR, but he didn't delete the `packages/eslint-config-custom` nor the "lost" `.eslintrc` files that exists on other parts of the project.

**Comment by ocodista** [comment]
The approach number doesn't work.

We can't use a single eslint file on the root, as this throws an error related to turborepo.

We should use the eslint-config-custom folder for keeping the shared config

image

**Pull request merged**
