### PR TITLE
Vitest unit test support

### PR DESCRIPTION
**Pull request by albertofp**
Added boilerplate for unit testing with vitest and vite

#35

### CODE REVIEW

**Comment by ocodista** [comment]
Thank you!

It seems to me that your files are not linted properly.

Would you mind running `turbo lint` on the root of the project to see if fixes?

Please also add the `test` command on the `turbo.json` as described here https://turbo.build/repo/docs/handbook/testing

**Comment by albertofp** [comment]
Done

**Review by ocodista — APPROVED** [review]
Thank you, this will help a lot!

**Comment by ocodista** [comment]
@albertofp Please resolve the conflicts and you're free to merge.

**Pull request merged**
