### PR TITLE
Refactor/header navbar

### PR DESCRIPTION
**Pull request by gabrielSouzaDevWeb**
logo changed to white color

### CODE REVIEW

**Comment by ocodista** [comment]
Hey, thanks for contributing!

While I think that the mobile version is better, I haven't really liked the new Desktop navbar

Before:
image

After
image


The purple is too chamative.

@anti-duhring @albertofp what do you think?

**Comment by albertofp** [comment]
Agreed, would prefer either white or the purple used for the submit button below

**Comment by anti-duhring** [comment]
> The purple is very flashy

Indeed. I would pick up the old version

**Comment by gahcalistro** [comment]
On mobile, I would recommend logo on the left and button on the right. Also item style could change according to each section. I can help with that if you want and the idea gets an approval.
@ocodista  @gabrielSouzaDevWeb

**Pull request closed without merging**
