### PR TITLE
Refactor: header component

### PR DESCRIPTION
**Pull request by kevinCubas**
This PR resolves the issue of the mobile menu appearing on large screens, as shown below.
Captura de tela 2023-11-04 010143

The expected behavior is for the mobile menu to be hidden on large screens, **even** when the "isMobileMenuOpen" state is 'true.'

In addition, this PR includes the following refactorings:
- Removal of redundant tailwind classes and consolidation into a single class.
- Replacement of the <a> tags with the Next.js Link component.

_The changes ensure that the mobile menu behaves correctly on large screens and improve code maintainability by eliminating repetitive classes and adopting the Link component for better navigation. It Enhances the user experience and code quality._

### CODE REVIEW

**Review by ocodista — APPROVED** [review]

**Comment by ocodista** [comment]
It doesn't seem to work on the preview.

**Review by ocodista — CHANGES_REQUESTED** [review]
preview not redirecting on large screens

**Comment by kevinCubas** [comment]
> preview not redirecting on large screens

working on it. The route defined in href is not being handled correctly by Next.js in a production environment.

**Comment by kevinCubas** [comment]
If it didn't work I'm changing back to anchor tags. 
_It's working on development env_

**Comment by ocodista** [comment]
@kevinCubas take a look, it doesn't seem to work here.

I remember we started with the `Link` component, maybe that's why we migrated to the <a> tag

**Comment by kevinCubas** [comment]
I couldn't replicate it locally, sometimes it works on the preview but there is some delay.

I found this, It seems to be a Next's internal issue:

https://github.com/vercel/next.js/issues/50807
https://github.com/vercel/next.js/issues/44139
https://github.com/vercel/next.js/issues/44295

Using the anchor tag may be the best solution for now, the important thing is to ensure that the mobile menu behaves correctly.

**Review by ocodista — APPROVED** [review]

**Pull request merged**
